on:
  release:
    types: [created, edited]

# strategy:
#   matrix:
#     platform: [windows, osx, html, linux]

env:
  PROJECT_NAME: godoobs-gwj22
  ITCH_GAME: godot-wild-jam-22
  ITCH_USER: godoobs

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download windows release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PROJECT_NAME }}--windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: push windows release to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PROJECT_NAME }}--windows.zip

  release_osx:
    runs-on: ubuntu-latest
    steps:
      - name: download osx release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PROJECT_NAME }}--osx.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: push osx release to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PROJECT_NAME }}--osx.zip
  
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download linux release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PROJECT_NAME }}--linux.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: push osx release to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PROJECT_NAME }}--osx.zip

  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: download html5 release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PROJECT_NAME }}--html.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: push html release to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PROJECT_NAME }}--html5.zip
